import turtle
import getpass

username = getpass.getuser()

turtle.addshape("trust the process.png")

t = turtle.Turtle()
t.getscreen().setup(1000, 800)
t.speed(20) # This number can be anywhere between 1 and 10
#turtle.getscreen().tracer(0)
#turtle.getscreen().update()
#t.shape("trust the process.png")
def gotorel(x,y):
    t.goto(t.pos() + turtle.Vec2D(x, y))

def rec(w,h,c):
    t.fillcolor(c)
    t.begin_fill()
    gotorel(w,0)
    gotorel(0, h)
    gotorel(-w, 0)
    gotorel(0, -h)
    t.end_fill()

def circ(r,c):
    t.fillcolor(c)
    t.begin_fill()
    t.circle(r)
    t.end_fill()

def trig(x1,y1,x2,y2,c):
    t.fillcolor(c)
    t.begin_fill()
    gotorel(x1,y1)
    gotorel(x2-x1,y2-y1)
    gotorel(-x2,-y2)
    t.end_fill()

t.penup()


t.goto(0,300)
t.write(f"Hello {username}", font=('Arial', 40, 'normal'))
t.goto(0,270)
t.write("happy holiday(s)!", font=('Arial', 25, 'normal'))
t.goto(0,240)
t.write("I hope you get lots of cool stuff", font=('Arial', 25, 'normal'))
t.goto(0,210)
t.write("and I hope you enjoy yourself!", font=('Arial', 25, 'normal'))
t.goto(0,180)
t.write("or dont", font=('Arial', 25, 'normal'))
t.goto(0,150)
t.write("- Aiden", font=('Arial', 25, 'normal'))
t.goto(-250,0)
t.shape("trust the process.png")
t.stamp()
t.shape("classic")
t.pencolor("white")
t.pendown()
t.fillcolor("white")
t.begin_fill()
t.forward(40)
t.left(90)
t.forward(10)
t.left(90)
t.forward(80)
t.left(90)
t.forward(10)
t.left(90)
t.forward(40)
t.end_fill()
t.penup()
gotorel(-30,10)
t.color("red")
t.fillcolor("red")
t.pendown()
t.begin_fill()
gotorel(30,75)
gotorel(30,-75)
gotorel(-60,0)
t.end_fill()
t.penup()
gotorel(30,70)
t.fillcolor("white")
t.begin_fill()
t.circle(5)
t.end_fill()
t.penup()
t.goto(-325,100)
rec(150,150,"red")
gotorel(62.5,0)
rec(25,150,"green")
gotorel(-62.5,62.5)
rec(150,25,"green")
gotorel(0,-62.5)
gotorel(75,150)
gotorel(-20,0)
circ(20,"gold")
gotorel(0,5)
circ(15,"white")
gotorel(0,-5)
gotorel(40,0)
circ(20,"gold")
gotorel(0,5)
circ(15,"white")
gotorel(-25,-5)
rec(10,10,"gold")
t.goto(250,-200)
def tree():
    rec(20,40,"brown")
    gotorel(-60,40)
    trig(70,70,140,0,"green")
    gotorel(5,20)
    trig(60,70,130,0,"green")
    gotorel(5,40)
    trig(60,90,120,0,"green")
    gotorel(60,90)
    t.shape("turtle")
    t.resizemode("user")
    t.shapesize(2, 2, 0)
    t.left(90)
    t.fillcolor("gold")
    t.color("yellow")
    t.stamp()
    t.right(90)
    t.shape("classic")
    t.resizemode("auto")
    gotorel(5,-30)
    circ(5,"red")
    gotorel(-20,-10)
    circ(5,"lime")
    gotorel(40,-30)
    circ(5,"yellow")
    gotorel(-60,-40)
    circ(5,"white")
    gotorel(70,-5)
    circ(5,"orange")
    gotorel(-50,30)
    circ(5,"blue")

tree()
gotorel(-80,30)
tree()
gotorel(-80,-180)
tree()

turtle.done()
